#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
alt=Mod1
Mod=Mod4
term=st
browser=firefox

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Control-q reload
hc keybind $Mod-q close
hc keybind $Mod-Shift-BackSpace spawn power
hc keybind $Mod-Return spawn $term

# Run launcher and emojis
hc keybind $Mod-space spawn dmenu_run
hc keybind $Mod-Shift-d spawn rofi -show drun
hc keybind $Mod-Menu spawn rofi -show emoji

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-p       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-bracketright use_index +1 --skip-visible
hc keybind $Mod-bracketleft  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-y floating toggle
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-t set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-t pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Tab                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-period         cycle_all +1
hc keybind $Mod-comma   cycle_all -1
hc keybind $Mod-Shift-c cycle
hc keybind $Mod-i jumpto urgent

# MPD and Audio
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +3%
hc keybind $alt-Up spawn pactl set-sink-volume 0 +3%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -3%
hc keybind $alt-Down spawn pactl set-sink-volume 0 -3%
hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind $alt-Shift-space spawn mpc toggle
hc keybind XF86AudioPlay spawn mpc toggle
hc keybind XF86AudioNext spawn mpc next
hc keybind $alt-Shift-Right spawn mpc next
hc keybind XF86AudioPrev spawn mpc prev
hc keybind $alt-Shift-Left spawn mpc prev
hc keybind $alt-Right spawn mpc vol +5
hc keybind $alt-Left spawn mpc vol -5
hc keybind $alt-$Mod-Return spawn $term -e ncmpcpp
hc keybind $alt-Control-v spawn $term -e pulsemixer
hc keybind $alt-bracetleft spwan mpc seek -10
hc keybind $alt-Shift-bracetleft spwan mpc seek -60
hc keybind $alt-bracetright spwan mpc seek +10
hc keybind $alt-Shift-bracetright spwan mpc seek +60
hc keybind $alt-apostrophe spawn mpc seek 0%
hc keybind $alt-Control-space spawn mpc single

# Brightness
hc keybind XF86MonBrightnessUp spwan xbacklight -inc 5%
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5%
hc keybind $Mod-$alt-minus spawn xbacklight -dec 5%
hc keybind $Mod-$alt-equal spawn xbacklight -inc 5%

# Screenshots
hc keybind $alt-Shift-s spawn maim -s ~/Data/screenshots/$(date +%Y-%m-%d-%s).png
hc keybind $alt-s spawn maim ~/Data/screenshots/$(date +%Y-%m-%d-%s).png

#Others
hc keybind XF86HomePage spawn $browser
hc keybind $alt-r spwan radio-listen
hc keybind $alt-Menu spwan radio-listen
hc keybind $alt-Shift-w spawn sxiv -q -o -t -r ~/Data/Media/wallpapers
hc keybind $Mod-Shift-g spwan gimp
hc keybind $Mod-grave spwan alacritty
hc keybind $Mod-Shift-x spawn pcmanfm
hc keybind $Mod-Shift-e spawn $term -e htop
hc keybind $Mod-w spwan $browser
hc keybind $Mod-Shift-v spawn minitube
hc keybind $Mod-c spawn galculator
hc keybind $Mod-Control-r spawn mpv --untimed --no-cache --no-osc --no-input-default-bindings --profile=low-latency --input-conf=/dev/null --title=webcam /dev/video0
hc keybind $Mod-Control-z spawn slock
hc keybind $alt-w spawn $term -e nmtui
hc keybind $Mod-d spawn clipgrab
hc keybind $Mod-e spawn emacsclient -c || emacs
hc keybind $Mod-a spawn $term -e ranger
hc keybind $Mod-slash spawn web-search
hc keybind $Mod-Shift-slash spawn browser-launch
hc keybind $Mod-Shift-w spawn open-bookmarks

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_active_color '#345F0Caa'
hc set frame_border_width 1
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.title_height 0
hc attr theme.title_when never
hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3  # space below the title's baseline
hc attr theme.active.color '#345F0Cef'
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.tab_color '#1F1F1Fdd'
hc attr theme.active.tab_color '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257dd'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 5
hc set frame_padding 7
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors


